version: "2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: 192.168.177.248/abs52121/freiendlyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:

